name: openjdk docker build & push

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-jobs:
    name: openjdk-build
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:
          -
            name: openjdk-19-jdk-alpine3.15
            image: dongjiang1989/openjdk
            file: ./openjdk/19/jdk/alpine3.15/Dockerfile
            platforms: linux/amd64
          -
            name: openjdk-19-jdk-alpine3.15
            image: dongjiang1989/openjdk
            file: ./openjdk/19/jdk/alpine3.15/Dockerfile
            platforms: linux/amd64
          -
            name: openjdk-25-jdk-oraclelinux8
            image: dongjiang1989/openjdk
            file: ./openjdk/25/jdk/oraclelinux8/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-25-jdk-oraclelinux9
            image: dongjiang1989/openjdk
            file: ./openjdk/25/jdk/oraclelinux9/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-25-jdk-bullseye
            image: dongjiang1989/openjdk
            file: ./openjdk/25/jdk/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-25-jdk-slim-bullseye
            image: dongjiang1989/openjdk
            file: ./openjdk/25/jdk/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-25-jdk-bookworm
            image: dongjiang1989/openjdk
            file: ./openjdk/25/jdk/bookworm/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-25-jdk-bookworm-slim
            image: dongjiang1989/openjdk
            file: ./openjdk/25/jdk/slim-bookworm/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-11-jdk-oraclelinux8
            image: dongjiang1989/openjdk
            file: ./openjdk/11/jdk/oraclelinux8/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-11-jdk-oraclelinux7
            image: dongjiang1989/openjdk
            file: ./openjdk/11/jdk/oraclelinux7/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-11-jdk-bullseye
            image: dongjiang1989/openjdk
            file: ./openjdk/11/jdk/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-11-jdk-slim-bullseye
            image: dongjiang1989/openjdk
            file: ./openjdk/11/jdk/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-11-jdk-buster
            image: dongjiang1989/openjdk
            file: ./openjdk/11/jdk/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-11-jdk-slim-buster
            image: dongjiang1989/openjdk
            file: ./openjdk/11/jdk/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-18-jdk-oraclelinux8
            image: dongjiang1989/openjdk
            file: ./openjdk/18/jdk/oraclelinux8/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-18-jdk-oraclelinux7
            image: dongjiang1989/openjdk
            file: ./openjdk/18/jdk/oraclelinux7/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-18-jdk-bullseye
            image: dongjiang1989/openjdk
            file: ./openjdk/18/jdk/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-18-jdk-slim-bullseye
            image: dongjiang1989/openjdk
            file: ./openjdk/18/jdk/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-18-jdk-buster
            image: dongjiang1989/openjdk
            file: ./openjdk/18/jdk/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-18-jdk-slim-buster
            image: dongjiang1989/openjdk
            file: ./openjdk/18/jdk/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-8-jdk-oraclelinux8
            image: dongjiang1989/openjdk
            file: ./openjdk/8/jdk/oraclelinux8/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-8-jdk-oraclelinux7
            image: dongjiang1989/openjdk
            file: ./openjdk/8/jdk/oraclelinux7/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-8-jdk-bullseye
            image: dongjiang1989/openjdk
            file: ./openjdk/8/jdk/bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-8-jdk-slim-bullseye
            image: dongjiang1989/openjdk
            file: ./openjdk/8/jdk/slim-bullseye/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-8-jdk-buster
            image: dongjiang1989/openjdk
            file: ./openjdk/8/jdk/buster/Dockerfile
            platforms: linux/amd64,linux/arm64
          -
            name: openjdk-8-jdk-slim-buster
            image: dongjiang1989/openjdk
            file: ./openjdk/8/jdk/slim-buster/Dockerfile
            platforms: linux/amd64,linux/arm64
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2 
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.image }}:${{ matrix.name }}
      - name: Test ${{ matrix.name }}
        run: |
          docker pull ${{ matrix.image}}:${{ matrix.name }}
          docker image inspect ${{ matrix.image}}:${{ matrix.name }}
